### ISSUE TITLE
No worker connected..

### ISSUE THREAD

**Issue by mcauto** [Gwenio/vscode-ava-test-adapter#18]
It is not working project by `npx create-nuxt-app <project_name>`

extension version: v0.4.1 
ava version: v2.4.0

![image](https://user-images.githubusercontent.com/15080806/67093822-67a63600-f1ed-11e9-8575-90095e8a438c.png)

![image](https://user-images.githubusercontent.com/15080806/67093747-47767700-f1ed-11e9-8c5e-cd9acda2428a.png)

![image](https://user-images.githubusercontent.com/15080806/67093770-54936600-f1ed-11e9-9ccc-e9e42058fd82.png)

![image](https://user-images.githubusercontent.com/15080806/67094032-e602d800-f1ed-11e9-846c-8b1c5050de03.png)

**Comment by starmandeluxe** [comment]
+1, I reproduced this on MacOS. Symptom is no tests show in the Test Explorer. 

However the extension is working on a Linux machine.

Since the OP posted a non-copyable screenshot, here is my log:

> [2019-10-30 08:07:51.483] [INFO] Test Explorer found
[2019-10-30 08:07:51.874] [INFO] Creating adapter for /Users/...
[2019-10-30 08:07:51.874] [INFO] Initializing AVA Adapter...
[2019-10-30 08:07:51.874] [INFO] Using default NodeJS: /usr/local/bin/node
[2019-10-30 08:07:51.875] [ERROR] Found invalid value for avaExplorer.nodePath { [ArgumentError: Any predicate failed with the following errors:

> Expected `nodePath` to be of type `undefined` but received type `string`
Expected string `nodePath` to not be empty
	at Object.r [as nodePath] (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:21168)
	at U.getNode (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56702)
	at U.setValue (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:58112)
	at new U (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56325)
	at new me (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:70294)
	at r.TestAdapterRegistrar.e.subscriptions.push.e [as adapterFactory] (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75580)
	at r.TestAdapterRegistrar.add (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1594)
	at new r.TestAdapterRegistrar (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1094)
	at exports.activate (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75569)] name: 'ArgumentError' }
[2019-10-30 08:07:51.880] [DEBUG] Spawning worker...
[2019-10-30 08:07:51.892] [INFO] Registering adapter for /Users/...
[2019-10-30 08:07:51.893] [INFO] Loading test files of /Users/...
[2019-10-30 08:07:51.893] [INFO] Initialization finished
[2019-10-30 08:08:01.895] [ERROR] { [CancelError: Attempt to connect to worker timed out.
	at E.cancel (/Users/.../.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:11931)] name: 'CancelError' }
[2019-10-30 08:08:01.897] [ERROR] No worker connected.

**Comment by cdaringe** [comment]
just because the other image and block quote format a bit funkily, here's my stack too :)

```
[2020-04-29 23:44:33.526] [INFO] Test Explorer found
[2020-04-29 23:44:33.543] [INFO] Creating adapter for /Users/c0d01a5/src/daedalus
[2020-04-29 23:44:33.543] [INFO] Initializing AVA Adapter...
[2020-04-29 23:44:33.543] [INFO] Using default NodeJS: /Users/c0d01a5/.nvm/versions/node/v12.16.1/bin/node
[2020-04-29 23:44:33.544] [ERROR] Found invalid value for avaExplorer.nodePath [Error [ArgumentError]: Any predicate failed with the following errors:
- Expected `nodePath` to be of type `undefined` but received type `string`
- Expected string `nodePath` to not be empty
	at Object.nodePath (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:21168)
	at U.getNode (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56702)
	at U.setValue (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:58112)
	at new U (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56325)
	at new me (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:70294)
	at r.TestAdapterRegistrar.adapterFactory (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75580)
	at r.TestAdapterRegistrar.add (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1594)
	at new r.TestAdapterRegistrar (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1094)
	at exports.activate (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75569)
	at async Promise.all (index 1)] {
  name: 'ArgumentError'
}
[2020-04-29 23:44:33.546] [DEBUG] Spawning worker...
[2020-04-29 23:44:33.550] [INFO] Registering adapter for /Users/c0d01a5/src/daedalus
[2020-04-29 23:44:33.551] [INFO] Loading test files of /Users/c0d01a5/src/daedalus
[2020-04-29 23:44:33.551] [INFO] Initialization finished
[2020-04-29 23:44:43.555] [ERROR] [O [CancelError]: Attempt to connect to worker timed out.
	at E.cancel (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:11931)] {
  name: 'CancelError'
}
[2020-04-29 23:44:43.555] [ERROR] No worker connected.
```

**Comment by skyrpex** [comment]
Got the same problem, don't know what to do :thinking:
