### ISSUE TITLE
Cannot find module 'get-port'

### ISSUE THREAD

**Issue by cdaringe** [Gwenio/vscode-ava-test-adapter#60]
# problem

```
Error: Cannot find module 'get-port'
Require stack:
- /Users/c0d01a5/src/daedalus/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/c0d01a5/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/child.js:18:381)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/c0d01a5/src/daedalus/noop.js' ]
```

**Comment by leolcao** [comment]
The same issue from me. I guest  this ava test adapter has not support AVA 3 yet, it may comes soon by watching the commits history. Let's wait

**Comment by cdaringe** [comment]
Get port is listed as a development dependency not a production dependency. My supposition is that these dependencies simply need to be moved in the package.json and a new release pushed
