### ISSUE TITLE
avaExplorer.nodePath [Error [ArgumentError]:

### ISSUE THREAD

**Issue by dcsan** [Gwenio/vscode-ava-test-adapter#80]
tried the extension, but can't see any results in the list of tests
i checked related output panel and see this:

```
[2020-07-14 22:44:19.312] [INFO] Test Explorer found
[2020-07-14 22:44:19.327] [INFO] Creating adapter for /Users/dc/dev/exiteer/xbot/server
[2020-07-14 22:44:19.327] [INFO] Initializing AVA Adapter...
[2020-07-14 22:44:19.327] [INFO] Using default NodeJS: /usr/local/bin/node
[2020-07-14 22:44:19.327] [ERROR] Found invalid value for avaExplorer.nodePath [Error [ArgumentError]: Any predicate failed with the following errors:
- Expected `nodePath` to be of type `undefined` but received type `string`
- Expected string `nodePath` to not be empty
	at Object.nodePath (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:21168)
	at U.getNode (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56702)
	at U.setValue (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:58112)
	at new U (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:56325)
	at new me (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:70294)
	at r.TestAdapterRegistrar.adapterFactory (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75580)
	at r.TestAdapterRegistrar.add (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1594)
	at new r.TestAdapterRegistrar (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:1094)
	at exports.activate (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:75569)
	at async Promise.all (index 1)
	at async Promise.all (index 0)] {
  name: 'ArgumentError'
}
[2020-07-14 22:44:19.329] [DEBUG] Spawning worker...
[2020-07-14 22:44:19.340] [INFO] Registering adapter for /Users/dc/dev/exiteer/xbot/server
[2020-07-14 22:44:19.341] [INFO] Loading test files of /Users/dc/dev/exiteer/xbot/server
[2020-07-14 22:44:19.341] [INFO] Initialization finished
[2020-07-14 22:44:29.341] [ERROR] [O [CancelError]: Attempt to connect to worker timed out.
	at E.cancel (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/main.js:18:11931)] {
  name: 'CancelError'
}
[2020-07-14 22:44:29.342] [ERROR] No worker connected.

```

**Comment by carmanchris31** [comment]
The expected behavior is supposed to be (per the docs):
> Ava Explorer: Node Path
> The path to the node executable to use. By default it will attempt to find it on your PATH, if it can't find it or if this option is set to `null`, it will use the one shipped with VS Code

**Comment by carmanchris31** [comment]
Issue appears to be with this line:
https://github.com/Gwenio/vscode-ava-test-adapter/blob/135a9b7b8dcec74c352543a72755f17319e49cf3/extension/adapter/src/config.ts#L117

nodePath is being defaulted to an empty string and therefore fails to meet the conditions of being either a non-empty string or undefined.

It would be better to treat an empty string and `undefined` the same (empty values).
